name: Update Biennial Update Report submissions
on:
  schedule:
    - cron:  '0 3 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          pip install csv-diff
      - name: Copy old version
        run: cp data/submissions-bur.csv data/submissions-bur-old.csv
      - name: Update data
        run: python scripts/process_bur.py
      - name: Diff files
        run: csv-diff data/submissions-bur-old.csv data/submissions-bur.csv  >> message.txt
      - name: Commit back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "<>"
          git config user.name "Update Bot"
          git checkout master
          git add data/submissions-bur.csv
          git commit -F message.txt
          git log -n 2
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master
