name: Update National Inventory Report submissions
on:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          pip install csv-diff
      - name: Update data
        run: python scripts/process.py 2019
      - name: Commit back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "<>"
          git config user.name "Update Bot"
          git checkout master
          git add data/submissions-2019.csv
          git commit -m "Update NIR submissions" && \
            git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master || true
          git log -n 2
